//go:build !ignore_autogenerated

/*
Copyright 2026 Maarlab Rethinking.
Licensed under the Apache License, Version 2.0 (the "License").
*/

// Code generated by controller-gen. DO NOT EDIT.
// (Hand-maintained until `make generate` is wired into CI.)

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ManagedFloatingIPs) DeepCopyInto(out *ManagedFloatingIPs) {
	*out = *in
	if in.Labels != nil {
		out2 := make(map[string]string, len(in.Labels))
		for k, v := range in.Labels {
			out2[k] = v
		}
		out.Labels = out2
	}
}

func (in *ManagedFloatingIPs) DeepCopy() *ManagedFloatingIPs {
	if in == nil {
		return nil
	}
	out := new(ManagedFloatingIPs)
	in.DeepCopyInto(out)
	return out
}

func (in *FloatingIPStatus) DeepCopyInto(out *FloatingIPStatus) { *out = *in }

func (in *FloatingIPStatus) DeepCopy() *FloatingIPStatus {
	if in == nil {
		return nil
	}
	out := new(FloatingIPStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerEgressGatewaySpec) DeepCopyInto(out *HetznerEgressGatewaySpec) {
	*out = *in
	if in.FloatingIPs != nil {
		out.FloatingIPs = append([]string(nil), in.FloatingIPs...)
	}
	if in.Managed != nil {
		out.Managed = in.Managed.DeepCopy()
	}
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	if in.DestinationCIDRs != nil {
		out.DestinationCIDRs = append([]string(nil), in.DestinationCIDRs...)
	}
	if in.ExcludedCIDRs != nil {
		out.ExcludedCIDRs = append([]string(nil), in.ExcludedCIDRs...)
	}
}

func (in *HetznerEgressGatewaySpec) DeepCopy() *HetznerEgressGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(HetznerEgressGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerEgressGatewayStatus) DeepCopyInto(out *HetznerEgressGatewayStatus) {
	*out = *in
	if in.FloatingIPs != nil {
		out.FloatingIPs = append([]FloatingIPStatus(nil), in.FloatingIPs...)
	}
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *HetznerEgressGatewayStatus) DeepCopy() *HetznerEgressGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(HetznerEgressGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerEgressGateway) DeepCopyInto(out *HetznerEgressGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HetznerEgressGateway) DeepCopy() *HetznerEgressGateway {
	if in == nil {
		return nil
	}
	out := new(HetznerEgressGateway)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerEgressGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerEgressGatewayList) DeepCopyInto(out *HetznerEgressGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]HetznerEgressGateway, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *HetznerEgressGatewayList) DeepCopy() *HetznerEgressGatewayList {
	if in == nil {
		return nil
	}
	out := new(HetznerEgressGatewayList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerEgressGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
