apiVersion: v2
name: hcloud-egress-gateway-controller
description: Stable egress source IPs (Hetzner floating IPs) for selected pods via Cilium Egress Gateway.
type: application
version: 0.2.5
appVersion: "0.2.5"
home: https://github.com/maarlab-rethinking/hcloud-egress-gateway-controller
sources:
  - https://github.com/maarlab-rethinking/hcloud-egress-gateway-controller
keywords: [hetzner, egress, floating-ip, cilium, egress-gateway]
